### ISSUE TITLE
Can not apply layout: No such layoutdagrefound; did you include its JS file?

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-dagre#22] opened 2017-03-03 00:11 UTC
Ref: https://github.com/cytoscape/cytoscape.js/issues/1738

----

I get this error when I'm trying to use the dagre layout

`Can not apply layout: No such layout `dagre` found; did you include its JS file? `

```js
import cytoscape from 'cytoscape'
import cydagre from 'cytoscape-dagre'
cydagre( cytoscape )

...
    var cy = cytoscape({
      container: document.getElementById('cy'),
      elements:{ nodes:graph.nodes, edges: graph.edges},
      layout: {
        name: 'dagre',
      },
    })
```

If I use the default layouts works fine.

**Comment by maxkfranz** [comment] 2017-03-03 00:15
@mj3cheun Would you please look into this when you're doing your Webpack testing?

**Comment by bernatfortet** [comment] 2017-03-03 23:05
thanks for switching threads @maxkfranz

**Comment by mj3cheun** [comment] 2017-03-08 15:13
Found the issue, the problem is webpack defaults to AMD over CommonJS, which requires all the dependencies (Dagre) to be passed in manually.

This issue is fixed in commit 7d26a2137184719232dd4842c5dcfe8827d84290 and will be published soon.

**Comment by luli-isa** [comment] 2017-04-04 14:58
When the commit will be publish ? I have the same error on my react project with webpack.

**Comment by maxkfranz** [comment] 2017-04-04 15:42
@mj3cheun is working on that now.  It will be published in the next day or so.  You can use a git url ref in your package.json in the meanwhile to use the latest code from master

**Comment by mj3cheun** [comment] 2017-04-04 20:14
Has been published. Use latest version 1.5.0.

**Closed** 2017-08-15 15:36 UTC
